services:
  - type: web
    name: brasil-burger-symfony
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_SECRET
        generateValue: true
      - key: DATABASE_URL
        value: postgresql://default:npg_7DL6FeUdkJYl@ep-bold-smoke-a2lga75q-pooler.eu-central-1.aws.neon.tech:5432/vercel_db?sslmode=require