# This file is the entry point to configure your own services.
services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Service d'upload d'images
    App\Service\Impl\FileUploaderService:
        arguments:
            $uploadsDirectory: '%kernel.project_dir%/public/uploads'
            $slugger: '@slugger'

    # Service de génération de numéros
    App\Service\GenerateNumeroService: '@App\Service\Impl\GenerateNumeroServiceImpl'
